### ISSUE TITLE
some wrong pattern in resGC$annotation 

### ISSUE THREAD

**Issue by yguitton** [rwehrens/metaMS#1] opened 2015-03-03 15:14 UTC
Hi Ron,

I am working on GC-MS data and tried to create some EICs and pspectra plot using the annotation slot.
It works quite fine,but for some unknown reasons it seems that sometimes some of the pspectra number noted in $annotation$fileX [,"pattern"] are not the right ones.
when i manually correct the $annotation (ie change the pspectra number in annotation)  all my plots are ok, 
in one of my test i add a pspectra associated to a 0 intensity inthe PeakTable but  if i am right a 0 in PeakTable means not annotated peak (not enough features or too low signal?
Have you seen such strange things? can it be due to one of my settings? 
Note: The resGC$PeakTable seems ok

All the best,
Yann Guitton

**Comment by rwehrens** [comment] 2015-03-04 05:45
Hi Yann, sounds unfamiliar... Could you send me some example data? I will look at them next week (away on holiday from today...)

Cheers,
Ron

<div>-------- Oorspronkelijk bericht --------</div><div>Van: Guitton Yann notifications@github.com </div><div>Datum:03-03-2015  16:14  (GMT+01:00) </div><div>Aan: rwehrens/metaMS metaMS@noreply.github.com </div><div>Onderwerp: [metaMS] some wrong pattern in resGC$annotation  (#1) </div><div>
</div>Hi Ron,

I am working on GC-MS data and tried to create some EICs and pspectra plot using the annotation slot.
It works quite fine,but for some unknown reasons it seems that sometimes some of the pspectra number noted in $annotation$fileX [,"pattern"] are not the right ones.
when i manually correct the $annotation (ie change the pspectra number in annotation) all my plots are ok, 
in one of my test i add a pspectra associated to a 0 intensity inthe PeakTable but if i am right a 0 in PeakTable means not annotated peak (not enough features or too low signal?
Have you seen such strange things? can it be due to one of my settings? 
Note: The resGC$PeakTable seems ok

All the best,
Yann Guitton

**Comment by yguitton** [comment] 2015-03-04 15:19
Hi Ron

Thanks for your answer, my be all that is only on my side.

here is a link to download the data and some other files
http://we.tl/KVqPzPml1c

files:
- data directory with the cdf used
- test_code.r my R code
- yannsettings. r (used by test_code)
  -annotationtest.r my function comparing PeakTable and annotation (used 
  in test_code)
  -resuts_files directory contains  some outputs made here in order 
  totryto understand the issue
  -PeakTable_vs_annotation is an  extraction from annotationtest output in 
  excel sheet with comments
- unknown 8 and Unkown 8 corrected are visualisation of pspectra and 
  EICS associated to unknown 8 (the corrected version is made manually by 
  changing the wrong annotation)

i have tried my annotationtest.r on metaMSdata examples and i also found 
some "errors" (code for that test inside test_code.r)

Happy holidays
Many thanks for your great package and for any help on that issue

All the best,
Yann

PS:*sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252
[3] LC_MONETARY=French_France.1252 LC_NUMERIC=C
[5] LC_TIME=French_France.1252

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets methods
[8] base

other attached packages:
  [1] metaMSdata_1.0.0    metaMS_1.3.4        CAMERA_1.20.0
  [4] igraph_0.7.1        xcms_1.40.0         mzR_1.10.7
  [7] Rcpp_0.11.3         Biobase_2.24.0      BiocGenerics_0.10.0
[10] rcdk_3.3.2          rJava_0.9-6         fingerprint_3.5.2

loaded via a namespace (and not attached):
  [1] acepack_1.3-3.3     cluster_2.0.1       codetools_0.2-10
  [4] DEoptimR_1.0-2      foreign_0.8-62      Formula_1.2-0
  [7] graph_1.42.0        grid_3.1.1          Hmisc_3.14-6
[10] iterators_1.0.7     lattice_0.20-29     latticeExtra_0.6-26
[13] Matrix_1.1-5        nnet_7.3-8          png_0.1-7
[16] RBGL_1.40.1         rcdklibs_1.5.8.4    RColorBrewer_1.1-2
[19] robustbase_0.92-3   rpart_4.1-8         splines_3.1.1
[22] stats4_3.1.1        survival_2.37-7     tools_3.1.1 *

Le 04/03/2015 06:45, Ron Wehrens a écrit :

> Hi Yann, sounds unfamiliar... Could you send me some example data? I 
> will look at them next week (away on holiday from today...)
> 
> Cheers,
> Ron
> 
> <div>-------- Oorspronkelijk bericht --------</div><div>Van: Guitton 
> Yann notifications@github.com </div><div>Datum:03-03-2015 16:14 
> (GMT+01:00) </div><div>Aan: rwehrens/metaMS 
> metaMS@noreply.github.com </div><div>Onderwerp: [metaMS] some wrong 
> pattern in resGC$annotation (#1) </div><div>
> </div>Hi Ron,
> 
> I am working on GC-MS data and tried to create some EICs and pspectra 
> plot using the annotation slot.
> It works quite fine,but for some unknown reasons it seems that 
> sometimes some of the pspectra number noted in $annotation$fileX 
> [,"pattern"] are not the right ones.
> when i manually correct the $annotation (ie change the pspectra number 
> in annotation) all my plots are ok,
> in one of my test i add a pspectra associated to a 0 intensity inthe 
> PeakTable but if i am right a 0 in PeakTable means not annotated peak 
> (not enough features or too low signal?
> Have you seen such strange things? can it be due to one of my settings?
> Note: The resGC$PeakTable seems ok
> 
> All the best,
> Yann Guitton
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/rwehrens/metaMS/issues/1#issuecomment-77100712.

## 

Yann GUITTON
Chercheur PostDoctorant
Projet IDEALG
LINA - équipe Combi (CNRS, Univ-Nantes, EMN, INRIA)
IRISA -  équipe Dyliss (CNRS, Univ-Rennes 1, INRIA)
+33 2 51 12 53 90 (Nantes)
+33 2 99 84 75 18 (Rennes)

**Comment by rwehrens** [comment] 2015-03-09 15:42
Hi Yann!

I have been downloading your stuff and indeed there seems to be 
something weird... if I understand correctly, the unknown patterns have 
very different retention times in the injections. This should definitely 
not be the case. I will investigate deeper in the coming days. Thanks 
for noticing this!

Cheers,
Ron

**Comment by rwehrens** [comment] 2015-03-10 08:34
Hi Yann,
I found the cause of the trouble. First of all I am happy to be able to 
tell you that the results of metaMS are correct, in the sense that all 
intensities and annotations and clusterings are consistent.

The problem is the following: in your test script you go deep into the 
bowels of xcms and CAMERA, and you use the pspectra slot to assess the 
individual peaks. Unfortunately, the numbering of the metaMS results is 
no longer exactly comparable to that slot, since all patterns with fewer 
peaks than the threshold have not been taken into account. That is, if 
the annotation for unknown 2 in the first injection (I am talking about 
the metaMS example data here) is -5, this does not mean that you should 
look at the 5th pspectra entry, but the 5th one that has at least 5 peaks:

> GCresults$xset[[1]]@pspectra[1:10]
> [[1]]
>   [1]    6    8   11   46   48   50   52   55   59   68   69   71   73 
>   94  127
> [16]  207  217  246  270  336  351  369  374  483  499  527  612  634 
> 792  808
> [31]  967 1159

[[2]]
[1]    1    9   56   66   70   72   74  370 2813

[[3]]
[1]    3 1144

[[4]]
[1]    4 2442 2650 2954 3925

[[5]]
[1]  2 58 67

[[6]]
[1]    5   10   65  505 4083

[[7]]
[1]  16  42  45  47  49  53 114 142

[[8]]
[1]    7   51   54 4134

[[9]]
[1]  57 213 538 621

[[10]]
  [1]   62  109  597  731  748 1068 1453 1719 1790 2330 2628 2791 3385 
3432 3910
[16] 3929

> an@groupInfo[an@pspectra[[7]], c("rt", "mz")]
>            rt       mz
> [1,] 294.847 37.56715
> [2,] 294.847 38.27416
> [3,] 294.847 39.30032
> [4,] 294.847 40.31551
> [5,] 295.066 41.30790
> [6,] 294.847 42.32637
> [7,] 294.847 53.02648
> [8,] 294.847 54.11002

And then you see that the retention time for this pattern exactly 
corresponds to the retention time in the GCresults$PseudoSpectra slot. 
Note that the numbering _does_ correspond with the msp patterns that are 
also returned.

I do agree that this is confusing, especially for those people who are 
used to looking into the depths of CAMERA objects, and will either put a 
remark in the manual pages (probably not a very good solution) or will 
try to fix it in another way.

Thanks again for bringing this to my attention!!!

Cheers,
Ron

**Comment by rwehrens** [comment] 2015-03-10 09:10
On 03/04/2015 04:19 PM, Guitton Yann wrote:

> Hi Ron
> 
> Thanks for your answer, my be all that is only on my side.
> 
> here is a link to download the data and some other files
> http://we.tl/KVqPzPml1c

Hi Yann,

I just included two small scripts that I used to debug the stuff. 
Interesting results. It also shows that you might want to play around 
with the settings for spectral similarity - we chose to only merge 
patterns into "unknowns" when the spectral similarity is very high 
indeed (match > .95) but maybe for other applications this is too high.

Cheers,
Ron

## from metaMS result to rtmatrix

## @param resGC from metaMS

## rtShift = accepted shift in seconds

## output mat annotation and matRT rt variation and matALL full comparison

## a 0 is OK

## a 1 is RT errors

## a 10 is NA error

## a 11 is RT + NA error

## Annotation table each value is a pcgrp associated to the unknown

## simplified version RW: we see that the unknowns do not have the

## same retention times! According to the settings the max difference

## should be .05 minutes, i.e., 3 seconds.

RWannotationtest <- function(resGC = resGC){
  ## what are the retention times of the unknowns?
  rtunkn <- 60*resGC$PeakTable[,"rt"]

  ## and what are the median retention times of the pspectra groups?
  ## Should be the same...
  mat <- matRT <-  matComparisonRT <- 
    matrix(NA, ncol=length(resGC$xset), nrow=nrow(resGC$PeakTable))

  ## First identify the patterns that are together from the different
  ## injections 
  for (j in 1:length(resGC$xset)){
    test <- resGC$annotation[[j]]
    mat[test[,2]*-1, j] <- test[,1]
  }
  colnames(mat) <- colnames(matRT) <- colnames(matComparisonRT) <-
    names(resGC$xset)

  settings <- resGC$settings
  allRTs <-
    lapply(1:length(resGC$xset),
           function(i) {
             an <- resGC$xset[[i]]
             allrts <- getPeaklist(an)[,"rt"]
             huhn <- an@pspectra[which(sapply(an@pspectra, length) >=
                                           metaSetting(resGC$settings,
                                                       "DBconstruction.minfeat"))]

```
         sapply(huhn, function(pp) median(allrts[pp]))
       })
```

  for (i in 1:4) 
    matRT[!is.na(mat[,i]), i] <- allRTs[[i]][ mat[!is.na(mat[,i]), i] ]

  matRT
}

require(metaMS)
cdfdir <- file.path(getwd(),"data")
files <- list.files(cdfdir, pattern = ".cdf",
                    full.names = TRUE, ignore.case = TRUE, recursive=TRUE)

source("yannsettings.r") 
resGCYann <- runGC(files=files, settings=YANN.GC, returnXset=TRUE)
source("annotationtest.r")
resAnnotation <- annotationtest(resGC=resGCYann, rtShift=15)

##with metaMS data and settings
require(metaMS)
require(metaMSdata)
data(FEMsettings)

cdfdir <- system.file("extdata", package = "metaMSdata")
cdffiles <- list.files(cdfdir, pattern = "_GC_",
                       full.names = TRUE, ignore.case = TRUE)
GCresults <- runGC(files = cdffiles,
                   settings = TSQXLS.GC,
                   returnXset=TRUE,
                   nSlaves = 4)

save(GCresults, file = "metaMSresults.RData")

require(metaMS)
load("metaMSresults.RData")
source("RWannotationtest.R")
resAnnotationmetaMS <- RWannotationtest(resGC = GCresults)
realRTs <- sapply(GCresults$PseudoSpectra, "[[", "rt") \* 60
cbind(resAnnotationmetaMS, realRTs)

## so at least this is consistent. Now we do see that a couple of

## unknowns are split into two patterns: e.g. unknown 1 and 13 may be

## the same.

GCresults$PseudoSpectra[c(1, 13)]
matchExpSpec(GCresults$PseudoSpectra[[1]]$pspectrum,
             GCresults$PseudoSpectra[-1],
             FALSE)

## this gives the following output:

## [1] 0.209135084 0.005453330 0.031456158 0.007302248 0.036081257 0.017772056

## [7] 0.000000000 0.030132730 0.001275202 0.005818480 0.016969142 0.875164938

## [13] 0.683681241 0.028012030 0.028591713 0.014783027 0.015427642

## we see that the match of pattern 1 with pattern 13 (12 in the list)

## is quite good, but not good enough to make the threshold of

## 0.95. Let's see what happens when we reduce this one to 0.75:

metaSetting(TSQXLS.GC, "betweenSamples.simthresh") <- .75
GCresults2 <- runGC(files = cdffiles,
                    settings = TSQXLS.GC,
                    returnXset=TRUE,
                    nSlaves = 4)
resAnnotationmetaMS2 <- RWannotationtest(resGC = GCresults2)
realRTs2 <- sapply(GCresults2$PseudoSpectra, "[[", "rt") \* 60
cbind(resAnnotationmetaMS2, realRTs2)

## and yes, the spectra have been merged into one unknown. Note that

## the same happens for the unknowns with rt = 1180 and 1142, and that

## additional unknowns are found

**Comment by yguitton** [comment] 2015-03-10 09:13
Hi Ron,

Many thanks for the time and energy spent on my issue, I was pretty sure 
that the peaktable was good and that i missed something in annotation.
I should have looked more carefully to your code before asking you.
I had to build that plotting function for a colleague which had doubts  
on the metaMS efficiency to show him how good the script is (and i 
failed because of that issue). And I am really happy to go back to him 
with a clear proof of the efficiency of your package.

Cheers
Yann

Le 10/03/2015 09:34, Ron Wehrens a écrit :

> Hi Yann,
> I found the cause of the trouble. First of all I am happy to be able to
> tell you that the results of metaMS are correct, in the sense that all
> intensities and annotations and clusterings are consistent.
> 
> The problem is the following: in your test script you go deep into the
> bowels of xcms and CAMERA, and you use the pspectra slot to assess the
> individual peaks. Unfortunately, the numbering of the metaMS results is
> no longer exactly comparable to that slot, since all patterns with fewer
> peaks than the threshold have not been taken into account. That is, if
> the annotation for unknown 2 in the first injection (I am talking about
> the metaMS example data here) is -5, this does not mean that you should
> look at the 5th pspectra entry, but the 5th one that has at least 5 peaks:
> 
> > GCresults$xset[[1]]@pspectra[1:10]
> > [[1]]
> > [1] 6 8 11 46 48 50 52 55 59 68 69 71 73
> > 94 127
> > [16] 207 217 246 270 336 351 369 374 483 499 527 612 634
> > 792 808
> > [31] 967 1159
> 
> [[2]]
> [1] 1 9 56 66 70 72 74 370 2813
> 
> [[3]]
> [1] 3 1144
> 
> [[4]]
> [1] 4 2442 2650 2954 3925
> 
> [[5]]
> [1] 2 58 67
> 
> [[6]]
> [1] 5 10 65 505 4083
> 
> [[7]]
> [1] 16 42 45 47 49 53 114 142
> 
> [[8]]
> [1] 7 51 54 4134
> 
> [[9]]
> [1] 57 213 538 621
> 
> [[10]]
> [1] 62 109 597 731 748 1068 1453 1719 1790 2330 2628 2791 3385
> 3432 3910
> [16] 3929
> 
> > an@groupInfo[an@pspectra[[7]], c("rt", "mz")]
> > rt mz
> > [1,] 294.847 37.56715
> > [2,] 294.847 38.27416
> > [3,] 294.847 39.30032
> > [4,] 294.847 40.31551
> > [5,] 295.066 41.30790
> > [6,] 294.847 42.32637
> > [7,] 294.847 53.02648
> > [8,] 294.847 54.11002
> 
> And then you see that the retention time for this pattern exactly
> corresponds to the retention time in the GCresults$PseudoSpectra slot.
> Note that the numbering _does_ correspond with the msp patterns that are
> also returned.
> 
> I do agree that this is confusing, especially for those people who are
> used to looking into the depths of CAMERA objects, and will either put a
> remark in the manual pages (probably not a very good solution) or will
> try to fix it in another way.
> 
> Thanks again for bringing this to my attention!!!
> 
> Cheers,
> Ron
> 
> On 03/04/2015 04:19 PM, Guitton Yann wrote:
> 
> > Hi Ron
> > 
> > Thanks for your answer, my be all that is only on my side.
> > 
> > here is a link to download the data and some other files
> > http://we.tl/KVqPzPml1c
> > 
> > files:
> > - data directory with the cdf used
> > - test_code.r my R code
> > - yannsettings. r (used by test_code)
> >   -annotationtest.r my function comparing PeakTable and annotation (used
> >   in test_code)
> >   -resuts_files directory contains some outputs made here in order
> >   totryto understand the issue
> >   -PeakTable_vs_annotation is an extraction from annotationtest output in
> >   excel sheet with comments
> > - unknown 8 and Unkown 8 corrected are visualisation of pspectra and
> >   EICS associated to unknown 8 (the corrected version is made manually by
> >   changing the wrong annotation)
> > 
> > i have tried my annotationtest.r on metaMSdata examples and i also found
> > some "errors" (code for that test inside test_code.r)
> > 
> > Happy holidays
> > Many thanks for your great package and for any help on that issue
> > 
> > All the best,
> > Yann
> > 
> > PS:*sessionInfo()
> > R version 3.1.2 (2014-10-31)
> > Platform: x86_64-w64-mingw32/x64 (64-bit)
> > 
> > locale:
> > [1] LC_COLLATE=French_France.1252 LC_CTYPE=French_France.1252
> > [3] LC_MONETARY=French_France.1252 LC_NUMERIC=C
> > [5] LC_TIME=French_France.1252
> > 
> > attached base packages:
> > [1] parallel stats graphics grDevices utils datasets methods
> > [8] base
> > 
> > other attached packages:
> > [1] metaMSdata_1.0.0 metaMS_1.3.4 CAMERA_1.20.0
> > [4] igraph_0.7.1 xcms_1.40.0 mzR_1.10.7
> > [7] Rcpp_0.11.3 Biobase_2.24.0 BiocGenerics_0.10.0
> > [10] rcdk_3.3.2 rJava_0.9-6 fingerprint_3.5.2
> > 
> > loaded via a namespace (and not attached):
> > [1] acepack_1.3-3.3 cluster_2.0.1 codetools_0.2-10
> > [4] DEoptimR_1.0-2 foreign_0.8-62 Formula_1.2-0
> > [7] graph_1.42.0 grid_3.1.1 Hmisc_3.14-6
> > [10] iterators_1.0.7 lattice_0.20-29 latticeExtra_0.6-26
> > [13] Matrix_1.1-5 nnet_7.3-8 png_0.1-7
> > [16] RBGL_1.40.1 rcdklibs_1.5.8.4 RColorBrewer_1.1-2
> > [19] robustbase_0.92-3 rpart_4.1-8 splines_3.1.1
> > [22] stats4_3.1.1 survival_2.37-7 tools_3.1.1 *
> > 
> > Le 04/03/2015 06:45, Ron Wehrens a écrit :
> > 
> > > Hi Yann, sounds unfamiliar... Could you send me some example data? I
> > > will look at them next week (away on holiday from today...)
> > > 
> > > Cheers,
> > > Ron
> > > 
> > > <div>-------- Oorspronkelijk bericht --------</div><div>Van: Guitton
> > > Yann notifications@github.com </div><div>Datum:03-03-2015 16:14
> > > (GMT+01:00) </div><div>Aan: rwehrens/metaMS
> > > metaMS@noreply.github.com </div><div>Onderwerp: [metaMS] some wrong
> > > pattern in resGC$annotation (#1) </div><div>
> > > </div>Hi Ron,
> > > 
> > > I am working on GC-MS data and tried to create some EICs and pspectra
> > > plot using the annotation slot.
> > > It works quite fine,but for some unknown reasons it seems that
> > > sometimes some of the pspectra number noted in $annotation$fileX
> > > [,"pattern"] are not the right ones.
> > > when i manually correct the $annotation (ie change the pspectra number
> > > in annotation) all my plots are ok,
> > > in one of my test i add a pspectra associated to a 0 intensity inthe
> > > PeakTable but if i am right a 0 in PeakTable means not annotated peak
> > > (not enough features or too low signal?
> > > Have you seen such strange things? can it be due to one of my 
> > > settings?
> > > Note: The resGC$PeakTable seems ok
> > > 
> > > All the best,
> > > Yann Guitton
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/rwehrens/metaMS/issues/1#issuecomment-77100712.
> > 
> > ## 
> > 
> > Yann GUITTON
> > Chercheur PostDoctorant
> > Projet IDEALG
> > LINA - équipe Combi (CNRS, Univ-Nantes, EMN, INRIA)
> > IRISA - équipe Dyliss (CNRS, Univ-Rennes 1, INRIA)
> > +33 2 51 12 53 90 (Nantes)
> > +33 2 99 84 75 18 (Rennes)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/rwehrens/metaMS/issues/1#issuecomment-77176400.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/rwehrens/metaMS/issues/1#issuecomment-78013349.

## 

Yann GUITTON
Chercheur PostDoctorant
Projet IDEALG
LINA - équipe Combi (CNRS, Univ-Nantes, EMN, INRIA)
IRISA -  équipe Dyliss (CNRS, Univ-Rennes 1, INRIA)
+33 2 51 12 53 90 (Nantes)
+33 2 99 84 75 18 (Rennes)

**Comment by yguitton** [comment] 2015-03-10 09:27
Hi Ron,

Great!
Again, many thanks

Cheers

Le 10/03/2015 10:10, Ron Wehrens a écrit :

> On 03/04/2015 04:19 PM, Guitton Yann wrote:
> 
> > Hi Ron
> > 
> > Thanks for your answer, my be all that is only on my side.
> > 
> > here is a link to download the data and some other files
> > http://we.tl/KVqPzPml1c
> 
> Hi Yann,
> 
> I just included two small scripts that I used to debug the stuff.
> Interesting results. It also shows that you might want to play around
> with the settings for spectral similarity - we chose to only merge
> patterns into "unknowns" when the spectral similarity is very high
> indeed (match > .95) but maybe for other applications this is too high.
> 
> Cheers,
> Ron
> 
> ## from metaMS result to rtmatrix
> 
> ## @param resGC from metaMS
> 
> ## rtShift = accepted shift in seconds
> 
> ## output mat annotation and matRT rt variation and matALL full
> 
> comparison
> 
> ## a 0 is OK
> 
> ## a 1 is RT errors
> 
> ## a 10 is NA error
> 
> ## a 11 is RT + NA error
> 
> ## Annotation table each value is a pcgrp associated to the unknown
> 
> ## simplified version RW: we see that the unknowns do not have the
> 
> ## same retention times! According to the settings the max difference
> 
> ## should be .05 minutes, i.e., 3 seconds.
> 
> RWannotationtest <- function(resGC = resGC){
> 
> ## what are the retention times of the unknowns?
> 
> rtunkn <- 60*resGC$PeakTable[,"rt"]
> 
> ## and what are the median retention times of the pspectra groups?
> 
> ## Should be the same...
> 
> mat <- matRT <- matComparisonRT <-
> matrix(NA, ncol=length(resGC$xset), nrow=nrow(resGC$PeakTable))
> 
> ## First identify the patterns that are together from the different
> 
> ## injections
> 
> for (j in 1:length(resGC$xset)){
> test <- resGC$annotation[[j]]
> mat[test[,2]*-1, j] <- test[,1]
> }
> colnames(mat) <- colnames(matRT) <- colnames(matComparisonRT) <-
> names(resGC$xset)
> 
> settings <- resGC$settings
> allRTs <-
> lapply(1:length(resGC$xset),
> function(i) {
> an <- resGC$xset[[i]]
> allrts <- getPeaklist(an)[,"rt"]
> huhn <- an@pspectra[which(sapply(an@pspectra, length) >=
> metaSetting(resGC$settings,
> "DBconstruction.minfeat"))]
> 
> sapply(huhn, function(pp) median(allrts[pp]))
> })
> for (i in 1:4)
> matRT[!is.na(mat[,i]), i] <- allRTs[[i]][ mat[!is.na(mat[,i]), i] ]
> 
> matRT
> }
> 
> require(metaMS)
> cdfdir <- file.path(getwd(),"data")
> files <- list.files(cdfdir, pattern = ".cdf",
> full.names = TRUE, ignore.case = TRUE, recursive=TRUE)
> 
> source("yannsettings.r")
> resGCYann <- runGC(files=files, settings=YANN.GC, returnXset=TRUE)
> source("annotationtest.r")
> resAnnotation <- annotationtest(resGC=resGCYann, rtShift=15)
> 
> ##with metaMS data and settings
> require(metaMS)
> require(metaMSdata)
> data(FEMsettings)
> 
> cdfdir <- system.file("extdata", package = "metaMSdata")
> cdffiles <- list.files(cdfdir, pattern = "_GC_",
> full.names = TRUE, ignore.case = TRUE)
> GCresults <- runGC(files = cdffiles,
> settings = TSQXLS.GC,
> returnXset=TRUE,
> nSlaves = 4)
> 
> save(GCresults, file = "metaMSresults.RData")
> 
> require(metaMS)
> load("metaMSresults.RData")
> source("RWannotationtest.R")
> resAnnotationmetaMS <- RWannotationtest(resGC = GCresults)
> realRTs <- sapply(GCresults$PseudoSpectra, "[[", "rt") \* 60
> cbind(resAnnotationmetaMS, realRTs)
> 
> ## so at least this is consistent. Now we do see that a couple of
> 
> ## unknowns are split into two patterns: e.g. unknown 1 and 13 may be
> 
> ## the same.
> 
> GCresults$PseudoSpectra[c(1, 13)]
> matchExpSpec(GCresults$PseudoSpectra[[1]]$pspectrum,
> GCresults$PseudoSpectra[-1],
> FALSE)
> 
> ## this gives the following output:
> 
> ## [1] 0.209135084 0.005453330 0.031456158 0.007302248 0.036081257
> 
> 0.017772056
> 
> ## [7] 0.000000000 0.030132730 0.001275202 0.005818480 0.016969142
> 
> 0.875164938
> 
> ## [13] 0.683681241 0.028012030 0.028591713 0.014783027 0.015427642
> 
> ## we see that the match of pattern 1 with pattern 13 (12 in the list)
> 
> ## is quite good, but not good enough to make the threshold of
> 
> ## 0.95. Let's see what happens when we reduce this one to 0.75:
> 
> metaSetting(TSQXLS.GC, "betweenSamples.simthresh") <- .75
> GCresults2 <- runGC(files = cdffiles,
> settings = TSQXLS.GC,
> returnXset=TRUE,
> nSlaves = 4)
> resAnnotationmetaMS2 <- RWannotationtest(resGC = GCresults2)
> realRTs2 <- sapply(GCresults2$PseudoSpectra, "[[", "rt") \* 60
> cbind(resAnnotationmetaMS2, realRTs2)
> 
> ## and yes, the spectra have been merged into one unknown. Note that
> 
> ## the same happens for the unknowns with rt = 1180 and 1142, and that
> 
> ## additional unknowns are found
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/rwehrens/metaMS/issues/1#issuecomment-78017839.

## 

Yann GUITTON
Chercheur PostDoctorant
Projet IDEALG
LINA - équipe Combi (CNRS, Univ-Nantes, EMN, INRIA)
IRISA -  équipe Dyliss (CNRS, Univ-Rennes 1, INRIA)
+33 2 51 12 53 90 (Nantes)
+33 2 99 84 75 18 (Rennes)

**Closed as completed** 2015-07-24 12:27 UTC
